# Set the base image
FROM ubuntu
# Dockerfile author/maintainer
MAINTAINER Name fancytyphoonkitty3@gmail.com
# Update app repo list and install pre-reqs
RUN apt-get update \
	&& apt-get install -y software-properties-common \
	&& add-apt-repository ppa:jonathonf/python-3.6 \
	&& apt-get update && apt-get install -y \
	python3.6 \
	python-pip \
	git-core \
	&& apt-get clean
# Clone partool and install pre-reqs
RUN git clone https://github.com/fancyTyphoonKitty/partool \
	&& pip install -r partool/requirements.txt